export const LOGO_URL="https://www.brandbucket.com/sites/default/files/logo_uploads/180314/large_fooditive.png"
export const CDN_URL="https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/"
export const MENU_API="https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=18.478849&lng=73.819062&restaurantId="
export const GITHUB_API="https://api.github.com/users/vaishnavi-mahajan"
export const SWIGGY_API="https://www.swiggy.com/dapi/restaurants/list/v5?lat=18.478849&lng=73.819062&is-seo-homepage-enabled=true&page_type=DESKTOP_WEB_LISTING"